---
service: prismic-lambda-webhook

plugins:
  - serverless-plugin-optimize

package:
  individually: true

provider:
  name: aws
  runtime: nodejs6.10
  memorySize: 128
  stage: ${opt:stage,self:custom.defaults.stage}
  region: ${opt:region,self:custom.defaults.region}
  profile: ${opt:profile,env:AWS_PROFILE,self:custom.defaults.profile}
  environment: ${file(./${opt:env,self:custom.defaults.env}.yml)}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - sns:ListTopics
        - sns:CreateTopic
        - sns:Publish
        - sns:Subscribe
      Resource:
        - arn:aws:sns:${self:provider.region}:*:PRISMIC_LAMBDA_WEBHOOK

custom:
  defaults:
    stage: dev
    region: eu-central-1
    env: env
    profile: default

functions:
  webhook:
    description: Handle Prismic.io webhook post and send SNS notification
    handler: functions/webhook.handle
    events:
      - http: POST webhook

  # EXAMPLE handler
  build:
    description: Run simple lambda triggered by SNS event
    handler: functions/build.handle
    events:
      - sns: PRISMIC_LAMBDA_WEBHOOK
